### ISSUE TITLE
LOTR[Bug]: 

### ISSUE THREAD

**Issue by Ruan548** [FalsePattern/EndlessIDs#78] opened 2022-12-28 16:30 UTC
### OS

Windows

### GPU

AMD

### Modpack (Optional)

Just LOTR and EndlessIDS

### Game log

[14:08:29] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:08:29] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:08:29] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[14:08:29] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[14:08:29] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Leandro\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy
[14:08:29] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from 00gasstation-mc1.7.10-0.5.1.jar
[14:08:29] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from endlessids-mc1.7.10-1.4.0.jar
[14:08:29] [main/INFO]: [io.gitlab.dwarfyassassin.lotrucp.core.UCPCoreMod:<clinit>:23]: LOTR-UCP: Found core mod.
[14:08:29] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:08:29] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[14:08:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Leandro/curseforge/minecraft/Instances/LOTR%202/mods/00gasstation-mc1.7.10-0.5.1.jar Service=LaunchWrapper Env=CLIENT
[14:08:29] [main/DEBUG]: Instantiating coremod class GasStationCore
[14:08:29] [main/INFO]: Initializing GasStationCore
[14:08:29] [main/TRACE]: coremod named GasStation Core Plugin is loading
[14:08:29] [main/DEBUG]: The coremod com.falsepattern.gasstation.core.GasStationCore requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[14:08:29] [main/DEBUG]: Enqueued coremod GasStation Core Plugin
[14:08:29] [main/DEBUG]: Instantiating coremod class IEPlugin
[14:08:29] [main/TRACE]: coremod named endlessids is loading
[14:08:29] [main/DEBUG]: The coremod com.falsepattern.endlessids.IEPlugin requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[14:08:29] [main/DEBUG]: Enqueued coremod endlessids
[14:08:29] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[14:08:29] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[14:08:29] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:08:29] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:08:29] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:08:29] [main/DEBUG]: Injecting coremod FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin} class transformers
[14:08:29] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.MarkerTransformer
[14:08:29] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.SideTransformer
[14:08:29] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
[14:08:29] [main/DEBUG]: Injection complete
[14:08:29] [main/DEBUG]: Running coremod plugin for FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin}
[14:08:29] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[14:08:30] [main/DEBUG]: Read 527 binary patches
[14:08:30] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[14:08:30] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:08:30] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[14:08:30] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:08:30] [main/DEBUG]: Injecting coremod FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin} class transformers
[14:08:30] [main/TRACE]: Registering transformer net.minecraftforge.classloading.FluidIdTransformer
[14:08:30] [main/DEBUG]: Injection complete
[14:08:30] [main/DEBUG]: Running coremod plugin for FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin}
[14:08:30] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[14:08:30] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[14:08:30] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[14:08:30] [main/INFO]: Compatibility level set to JAVA_8
[14:08:30] [main/INFO]: Development environment NOT detected! Skipping dev hotfixes...
[14:08:30] [main/INFO]: Initialised Mixin FML Remapper Adapter with cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@5ac86ba5
[14:08:30] [main/DEBUG]: Injecting coremod GasStation Core Plugin {com.falsepattern.gasstation.core.GasStationCore} class transformers
[14:08:30] [main/DEBUG]: Injection complete
[14:08:30] [main/DEBUG]: Running coremod plugin for GasStation Core Plugin {com.falsepattern.gasstation.core.GasStationCore}
[14:08:30] [main/DEBUG]: Running coremod plugin GasStation Core Plugin
[14:08:30] [main/DEBUG]: Coremod plugin class GasStationCore run successfully
[14:08:30] [main/DEBUG]: Injecting coremod endlessids {com.falsepattern.endlessids.IEPlugin} class transformers
[14:08:30] [main/TRACE]: Registering transformer com.falsepattern.endlessids.asm.IETransformer
[14:08:30] [main/DEBUG]: Injection complete
[14:08:30] [main/DEBUG]: Running coremod plugin for endlessids {com.falsepattern.endlessids.IEPlugin}
[14:08:31] [main/DEBUG]: Running coremod plugin endlessids
[14:08:31] [main/DEBUG]: Coremod plugin class IEPlugin run successfully
[14:08:31] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:08:31] [main/DEBUG]: Injecting coremod falsepatternlib {com.falsepattern.lib.internal.asm.CoreLoadingPlugin} class transformers
[14:08:31] [main/TRACE]: Registering transformer com.falsepattern.lib.internal.asm.FPTransformer
[14:08:31] [main/DEBUG]: Injection complete
[14:08:31] [main/DEBUG]: Running coremod plugin for falsepatternlib {com.falsepattern.lib.internal.asm.CoreLoadingPlugin}
[14:08:31] [main/DEBUG]: Running coremod plugin falsepatternlib
[14:08:31] [main/DEBUG]: Coremod plugin class CoreLoadingPlugin run successfully
[14:08:31] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[14:08:31] [main/DEBUG]: Loaded 57 rules from AccessTransformer config file fml_at.cfg
[14:08:31] [main/DEBUG]: Loaded 89 rules from AccessTransformer config file forge_at.cfg
[14:08:31] [main/DEBUG]: Validating minecraft
[14:08:31] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:08:31] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[14:08:31] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[14:08:31] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[14:08:31] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[14:08:31] [main/INFO]: Transforming makamys.mixingasm.MixinConfigPlugin to fit current mixin environment.
[14:08:31] [main/WARN]: MixinEnvironment::addTransformerExclusion is deprecated!
[14:08:31] [main/WARN]: MixinEnvironment::addTransformerExclusion is deprecated!
[14:08:31] [main/WARN]: MixinEnvironment::addTransformerExclusion is deprecated!
[14:08:31] [main/WARN]: MixinEnvironment::addTransformerExclusion is deprecated!
[14:08:31] [main/INFO]: Transforming com.falsepattern.endlessids.mixin.plugin.MixinPlugin to fit current mixin environment.
[14:08:31] [main/INFO]: Transforming com.falsepattern.lib.mixin.IMixinPlugin to fit current mixin environment.
[14:08:31] [main/INFO]: Jar not found for ABYSSALCRAFT
[14:08:31] [main/INFO]: Jar not found for AROCKETRY
[14:08:31] [main/INFO]: Jar not found for ATG
[14:08:31] [main/INFO]: Jar not found for ANTIQUEATLAS
[14:08:31] [main/INFO]: Jar not found for ANTIIDCONFLICT
[14:08:31] [main/INFO]: Jar not found for BOP
[14:08:31] [main/INFO]: Jar not found for BIOMETWEAKER
[14:08:31] [main/INFO]: Jar not found for BIOMEWAND
[14:08:31] [main/INFO]: Jar not found for BUILDCRAFT
[14:08:31] [main/INFO]: Jar not found for COFHLIB
[14:08:31] [main/INFO]: Jar not found for COMPACTMACHINES
[14:08:31] [main/INFO]: Jar not found for DARKWORLD
[14:08:31] [main/INFO]: Jar not found for DRAGONAPI
[14:08:31] [main/INFO]: Jar not found for EB
[14:08:31] [main/INFO]: Jar not found for ENDERLICIOUS
[14:08:31] [main/INFO]: Jar not found for EREBUS
[14:08:31] [main/INFO]: Jar not found for EXTRAPLANETS
[14:08:31] [main/INFO]: Jar not found for EXTRAUTILITIES
[14:08:31] [main/INFO]: Jar not found for FUTUREPACK
[14:08:31] [main/INFO]: Jar not found for GALACTICRAFTCORE
[14:08:31] [main/INFO]: Jar not found for GALAXYSPACE
[14:08:31] [main/INFO]: Jar not found for HIGHLANDS
[14:08:31] [main/INFO]: Jar not found for ICG
[14:08:31] [main/INFO]: Attempting to add C:\Users\Leandro\curseforge\minecraft\Instances\LOTR 2\mods\LOTRMod+v36.14.jar to the URL Class Path
[14:08:31] [main/INFO]: Jar not found for MFQM
[14:08:31] [main/INFO]: Jar not found for NATURESCOMPASS
[14:08:31] [main/INFO]: Jar not found for NETHERLICIOUS
[14:08:31] [main/INFO]: Jar not found for NOMADICTENTS
[14:08:31] [main/INFO]: Jar not found for RANDOMTHINGS
[14:08:31] [main/INFO]: Jar not found for RTG
[14:08:31] [main/INFO]: Jar not found for RWG
[14:08:31] [main/INFO]: Jar not found for THAUMCRAFT
[14:08:31] [main/INFO]: Jar not found for TROPICRAFT
[14:08:31] [main/INFO]: Jar not found for TWILIGHTFOREST
[14:08:31] [main/INFO]: Jar not found for UBC
[14:08:31] [main/INFO]: Jar not found for WITCHERY
[14:08:31] [main/INFO]: Jar not found for WORLDEDIT
[14:08:31] [main/INFO]: Could not find AbyssalCraft! Skipping integration....
[14:08:31] [main/INFO]: Could not find Advanced Rocketry! Skipping integration....
[14:08:31] [main/INFO]: Could not find Alternate Terrain Generation! Skipping integration....
[14:08:31] [main/INFO]: Could not find Antique Atlas! Skipping integration....
[14:08:31] [main/INFO]: Could not find Anti ID Conflict! Skipping integration....
[14:08:31] [main/INFO]: Could not find Biomes O' Plenty! Skipping integration....
[14:08:31] [main/INFO]: Could not find Biome Tweaker! Skipping integration....
[14:08:31] [main/INFO]: Could not find Biome Wand! Skipping integration....
[14:08:31] [main/INFO]: Could not find BuildCraft! Skipping integration....
[14:08:31] [main/INFO]: Could not find CoFH Lib! Skipping integration....
[14:08:31] [main/INFO]: Could not find Compact Machines! Skipping integration....
[14:08:31] [main/INFO]: Could not find Dark World! Skipping integration....
[14:08:31] [main/INFO]: Could not find DragonAPI! Skipping integration....
[14:08:31] [main/INFO]: Could not find Enhanced Biomes! Skipping integration....
[14:08:31] [main/INFO]: Could not find Enderlicious! Skipping integration....
[14:08:31] [main/INFO]: Could not find The Erebus! Skipping integration....
[14:08:31] [main/INFO]: Could not find Extra Planets! Skipping integration....
[14:08:31] [main/INFO]: Could not find Extra Utilities! Skipping integration....
[14:08:31] [main/INFO]: Could not find Futurepack! Skipping integration....
[14:08:31] [main/INFO]: Could not find GalactiCraftCore! Skipping integration....
[14:08:31] [main/INFO]: Could not find GalaxySpace! Skipping integration....
[14:08:31] [main/INFO]: Could not find Highlands! Skipping integration....
[14:08:31] [main/INFO]: Could not find Immersive Cavegen! Skipping integration....
[14:08:31] [main/INFO]: Found LOTR Mod! Integrating now...
[14:08:31] [main/INFO]: Could not find More Fun Quicksand Mod! Skipping integration....
[14:08:31] [main/INFO]: Could not find Nature's Compass! Skipping integration....
[14:08:31] [main/INFO]: Could not find Netherlicious! Skipping integration....
[14:08:31] [main/INFO]: Could not find Nomadic Tents! Skipping integration....
[14:08:31] [main/INFO]: Could not find Random Things! Skipping integration....
[14:08:31] [main/INFO]: Could not find Realistic Terrain Generation! Skipping integration....
[14:08:31] [main/INFO]: Could not find Realistic World Gen! Skipping integration....
[14:08:31] [main/INFO]: Could not find Thaumcraft! Skipping integration....
[14:08:31] [main/INFO]: Could not find Tropicraft! Skipping integration....
[14:08:31] [main/INFO]: Could not find Twilight Forest! Skipping integration....
[14:08:31] [main/INFO]: Could not find Underground Biomes Constructs! Skipping integration....
[14:08:31] [main/INFO]: Could not find Witchery! Skipping integration....
[14:08:31] [main/INFO]: Could not find WorldEdit! Skipping integration....
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.storage.AnvilChunkLoaderMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.storage.ChunkMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.storage.ExtendedBlockStorageMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.storage.ItemStackMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.networking.PacketBufferMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.networking.S21PacketChunkDataMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.networking.S22PacketMultiBlockChangeMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.networking.S24PacketBlockActionMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.networking.S26PacketMapChunkBulkMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.biome.BiomeDictionaryMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.biome.BiomeGenBaseMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.misc.BlockFireMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.misc.ItemInWorldManagerMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.misc.StatListMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.misc.WorldMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.worldgen.GenLayerRiverMixMixin
[14:08:31] [main/INFO]: Loading mixin: common.vanilla.worldgen.GenLayerVoronoiZoomMixin
[14:08:31] [main/INFO]: Loading mixin: client.vanilla.ChunkMixin
[14:08:31] [main/INFO]: Loading mixin: client.vanilla.NetHandlerPlayClientMixin
[14:08:31] [main/INFO]: Loading mixin: client.vanilla.PlayerControllerMPMixin
[14:08:31] [main/INFO]: Loading mixin: client.vanilla.RenderGlobalMixin
[14:08:31] [main/INFO]: Loading mixin: common.lotr.LOTRBiomeVariantStorageMixin
[14:08:31] [main/INFO]: Loading mixin: common.lotr.LOTRChunkProviderMixin
[14:08:31] [main/INFO]: Loading mixin: common.lotr.LOTRChunkProviderUtumnoMixin
[14:08:31] [main/INFO]: Loading mixin: common.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin
[14:08:31] [main/INFO]: Loading mixin: common.lotr.LOTRWorldChunkManagerMixin
[14:08:31] [main/FATAL]: Mixin prepare failed preparing common.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin in mixins.endlessids.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:864) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:850) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:795) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:567) [00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [00gasstation-mc1.7.10-0.5.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1313) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	... 17 more
[14:08:31] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.endlessids.json:common.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin] from phase [DEFAULT] in config [mixins.endlessids.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:584) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:569) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:864) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:850) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:795) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:567) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1313) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:850) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:795) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:567) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[00gasstation-mc1.7.10-0.5.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
[14:08:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:08:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[14:08:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[14:08:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[14:08:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:971)
[14:08:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[14:08:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Description

The game dont launch, Erro Code 1

**Comment by FalsePattern** [comment] 2022-12-28 16:31
Duplicate of #33

**Closed by FalsePattern** 2022-12-28 16:31 UTC
