### ISSUE TITLE
[Compatibility Request]: Bug with Decorative Video Game Systems

### ISSUE THREAD

**Issue by branman5949** [FalsePattern/EndlessIDs#68] opened 2022-11-11 04:36 UTC
### Other mod's name

Decorative Video Game Systems

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/decorative-video-game-systems/files/2255796

### Other mod's license

All Rights Reserved

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9986507/fml-client-latest.log)

### Description

When i place a block/decoration from the decorative video game systems mod and go to close and save the world the decorations/blocks won't save and aren't present as if i never placed them. 
![2022-11-10_23 29 32](https://user-images.githubusercontent.com/106054097/201264129-e1222954-29f4-471d-a1bf-7bfd20ec1925.png)
![2022-11-10_23 33 37](https://user-images.githubusercontent.com/106054097/201264142-a5cf807d-26f9-4c67-b124-4f19a11d69ce.png)

**Comment by FalsePattern** [comment] 2022-12-27 14:23
This is caused by that mod not registering its TileEntities properly. Not a bug in EndlessIDs, won't fix.

**Closed by FalsePattern** 2022-12-27 14:23 UTC
