### ISSUE TITLE
[Compatibility Request]: GregTech

### ISSUE THREAD

**Issue by epicgamingman** [FalsePattern/EndlessIDs#30] opened 2022-07-23 14:45 UTC
### Other mod's name

GregTech

### Other mod's homepage

https://gregtech.overminddl1.com/

### Other mod's license

Other open source license (please specify in the description)

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9173985/fml-client-latest.log)

### Description

This Mod is licensed under the [GNU Lesser General Public License](https://github.com/GregTech6/gregtech6/blob/master/LICENSE). All assets, unless otherwise stated, are dedicated to the public domain according to the [CC0 1.0 Universal Public Domain Dedication](https://github.com/GregTech6/gregtech6/blob/master/src/main/resources/LICENSE.assets). Any assets containing the [GregTech logo](https://github.com/GregTech6/gregtech6/blob/master/src/main/resources/logos) or any derivative of it are licensed under the [Creative Commons Attribution-NonCommercial 4.0 International Public License](https://github.com/GregTech6/gregtech6/blob/master/src/main/resources/LICENSE.logos).

**Comment by FalsePattern** [comment] 2022-07-23 18:53
Duplicate of #28, fix on the way

**Closed by FalsePattern** 2022-07-23 18:53 UTC
